### ISSUE TITLE
app doesn't open

### ISSUE THREAD

**Issue by sherifmousa85** [amirisback/sticker-whatsapp#3]
I pulled the latest project update and after generate apk and installed on phone this app doesn't open

**Comment by amirisback** [comment]
can you tell me what you changed? better if detailed

**Comment by sherifmousa85** [comment]
> can you tell me what you changed? better if detailed

I didn't make any changes. just pulled the latest project update and generate apk and installed on phone
i use
android studio version Android Studio 4.2.1
Windows 10

**Comment by amirisback** [comment]
try change 4.2.2 to 4.2.1 in this code https://github.com/amirisback/sticker-whatsapp/blob/master/build.gradle

**Comment by sherifmousa85** [comment]
> 4.2.2 to 4.2.1

i did it but still not working

**Comment by amirisback** [comment]
i have fixed the problem about admob by updating the new library, and i have tested it. please for re-pull latest commit
